# Generated by Django 5.0 on 2024-01-08 10:48

import social_site_app.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=social_site_app.models.post.generate_uuid_filename),
        ),
    ]
