# Generated by Django 5.0 on 2024-01-09 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site_app', '0003_alter_userpost_created_alter_userpost_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
