# Generated by Django 5.0 on 2024-01-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site_app', '0005_remove_userprofile_profile_image_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
