# Generated by Django 5.0 on 2024-01-03 06:42

import social_site_app.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site_app', '0006_alter_userprofile_address_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=social_site_app.models.profile.generate_uuid_filename),
        ),
    ]
